version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }
  local_pgadmin_data: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: corner_case_local_django
    container_name: corner_case_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: corner_case_production_postgres
    container_name: corner_case_postgres
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres


  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "53603:53603"
      - "8001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - local_pgadmin_data:/var/lib/pgadmin
