# Generated by Django 3.1.12 on 2021-07-06 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 6)),
            preserve_default=False,
        ),
    ]
